config/routes.rb
Rails.application.routes.draw do
  resources :guitars
  resources :pickups
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :guitars, only: %i[index show create]
      resources :pickups, only: %i[index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  has_one_attached :photo
  belongs_to :neck_pickup, class_name: 'Pickup', foreign_key: :neck_pickup_id, optional: true
  belongs_to :bridge_pickup, class_name: 'Pickup', foreign_key: :bridge_pickup_id, optional: true
  belongs_to :center_pickup, class_name: 'Pickup', foreign_key: :center_pickup_id, optional: true
  validates :name, presence: true
  validates :brand, presence: true
  CATEGORIES = [ ['brand', 'Brand'], ['name', 'Name'], ['year', 'Year'], ['serial_number', 'Serial Number'], ['made_in', 'Country'], ['color', 'Color'], ['artist', 'Artist'], ['price', 'Price'], ['purchase_date', 'Purchase Date'], ['body_wood', 'Body Wood'], ['body_top_wood', 'Body Top Wood'], ['body_finish', 'Body Finish'], ['neck_wood', 'Neck Wood'], ['fingerboard_wood', 'Fingerboard Wood'], ['scale_length', 'Scale Length'], ['frets_number', 'Frets Number'], ['frets_type', 'Frets Type'], ['neck_shape', 'Neck Shape'], ['neck_radius', 'Neck Radius'], ['neck_width_nut', 'Neck Width Nut'], ['neck_width_last_fret', 'Neck Width Last Fret'], ['neck_finish', 'Neck Finish'], ['neck_attachment', 'Neck Attachment'], ['nut_material', 'Nut Material'], ['inlays', 'Inlays'], ['pickups_configuration', 'Pickups Configuration'], ['neck_pickup_id', 'Neck Pickup'], ['center_pickup_id', 'Center Pickup'], ['bridge_pickup_id', 'Bridge Pickup'], ['bridge', 'Bridge'], ['tuning_machines', 'Tuning Machines']].freeze
end

app/models/guitar_pickup.rb
class GuitarPickup < ApplicationRecord
  belongs_to :guitar
  belongs_to :pickup
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  has_many :guitars

  CATEGORIES = [["brand", 'Brand'], ["name", 'Name'], ["product_name", 'Product Name'], ["output", 'Output'], ["resistance", 'Resistance'], ["bass", 'Bass'], ["low_middle", 'Low Middle'], ["high_middle", 'High Middle'], ["treble", 'Trebble'], ["pickup_type", 'Pickup Type'], ["magnet", 'Magnet'], ["active", 'Active']].freeze
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/guitars_controller.rb
class Api::V1::GuitarsController < ActionController::Base
  def index
    # @guitars = Guitar.where(user_id: current_user.id).order(name: :asc).group_by(&:brand);
    @guitars = Guitar.where(user_id: current_user.id).order(brand: :asc).order(name: :asc)
    render json: @guitars
  end

  def show
    @guitar = Guitar.find(params[:id])
    render json: @guitar
  end

  def create
    @guitar = Guitar.create(guitar_params)
    render json: @guitar
  end

  private

  def guitar_params
    params.require(:guitar).permit(:name, :brand, :year, :user_id, :photos)
  end
end

app/controllers/api/v1/pickups_controller.rb
class Api::V1::PickupsController < ActionController::Base
  def index
    @pickups = Pickup.order(created_at: :desc)
    render json: @pickups
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :set_guitar, only: %i[ show edit update destroy ]

  # GET /guitars or /guitars.json
  def index
    @guitars = Guitar.where(user_id: current_user.id).order(brand: :asc).order(name: :asc)
    @guitars_categories = Guitar::CATEGORIES
    @pickups_categories = Pickup::CATEGORIES
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="GuitarList.xlsx"'
      }
    end
  end

  # GET /guitars/1 or /guitars/1.json
  def show
  end

  # GET /guitars/new
  def new
    require_relative "../assets/data/brands"
    require_relative "../assets/data/countries"
    @guitar = Guitar.new
    @pickups = Pickup.all
  end

  # GET /guitars/1/edit
  def edit
    @pickups = Pickup.all
    require_relative "../assets/data/brands"
    require_relative "../assets/data/countries"
  end

  # POST /guitars or /guitars.json
  def create
    @guitar = Guitar.new(guitar_params)
    @guitar.user_id = current_user.id
    upload_image(@guitar, params) if params[:guitar][:photos]
    @guitar.photo_id = @guitar.photo.key if @guitar.photo.attached?
    respond_to do |format|
      if @guitar.save
        format.html { redirect_to root_path, notice: "Guitar was successfully created." }
        format.json { render :show, status: :created, location: @guitar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guitars/1 or /guitars/1.json
  def update
    respond_to do |format|
      upload_image(@guitar, params[:guitar][:photos0], 0) if params[:guitar][:photos0]
      upload_image(@guitar, params[:guitar][:photos1], 1) if params[:guitar][:photos1]
      upload_image(@guitar, params[:guitar][:photos2], 2) if params[:guitar][:photos2]
      upload_image(@guitar, params[:guitar][:photos3], 3) if params[:guitar][:photos3]
      if @guitar.update(guitar_params)
        @guitar.photo_id = @guitar.photo.key if @guitar.photo.attached?
        @guitar.save
        format.html { redirect_to root_path, notice: "Guitar was successfully updated." }
        format.json { render :show, status: :ok, location: @guitar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guitars/1 or /guitars/1.json
  def destroy
    @guitar.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Guitar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_guitar
    @guitar = Guitar.find(params[:id])
  end

  def guitar_params
    params.require(:guitar).permit(:name, :brand, :year, :photo, :color, :body_wood, :body_finish, :neck_wood, :body_top_wood, :fingerboard_wood, :bridge, :scale_length, :frets_number, :frets_type, :neck_shape, :neck_radius, :neck_width_nut, :neck_width_last_fret, :neck_finish, :neck_attachment, :nut_material, :tuning_machines, :serial_number, :made_in, :artist, :pickups_configuration, :neck_pickup_id, :center_pickup_id, :bridge_pickup_id, :purchase_date, :price, :photos_ids)
  end

  def upload_image(guitar, photo, index)
    Cloudinary::Uploader.upload(photo.path, folder: 'GuitarList/', public_id: "#{guitar.name.gsub(' ', '')}-#{index}", overwrite: true)
    guitar.photos_ids[index] ? guitar.photos_ids[index] = "#{guitar.name.gsub(' ', '')}-#{index}#{photo.content_type.gsub('image/', '.')}"
    : guitar.photos_ids[guitar.photos_ids.length] = "#{guitar.name.gsub(' ', '')}-#{index}#{photo.content_type.gsub('image/', '.')}"
    guitar.save
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  # GET /guitars/new
  def new
    require_relative "../assets/data/pickup_brands"
    @pickup = Pickup.new
  end

  # POST /guitars or /guitars.json
  def create
    @pickup = Pickup.new(pickup_params)
    if @pickup.save
      redirect_to guitars_path, notice: "Pickup was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def pickup_params
    params.require(:pickup).permit(:brand, :name, :product_name, :output, :neck, :center, :bridge, :resistance, :bass, :middle, :treble, :type, :magnet, :active, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guitars/_form.html.erb
<%= simple_form_for @guitar do |f| %>
  <%#= @guitar.new_record? %>
  <div class="row">
    <div class="col-md">
      <div class="form__title form__title__infos" data-name="form__infos">
        <%= image_tag("icon-guitar-misc.png") %>
        <h4>Infos</h4>
        <i class="fa-solid fa-angle-down" id="form__infos__icon"></i>
      </div>
      <div class="form__infos form__container form__hidden">
        <div class="form__content">
        <%= f.input :brand, collection: BRANDS.sort %>
        <%= f.input :name %>
        <%= f.input :year, collection: 1940..Time.now.year %>
        <%= f.input :serial_number %>
        <%= f.input :made_in, collection: COUNTRIES.sort, label:'Country' %>
        <%= f.input :artist %>
        <%= f.input :purchase_date, collection: 1950..Time.now.year %>
        <%= f.input :price, label: 'List Price ($)' %>
        </div>
      </div>
      <div class="form__title form__title__body" data-name="form__body">
        <%= image_tag("icon-guitar-body.png")%>
        <h4>Body</h4>
        <i class="fa-solid fa-angle-down" id="form__body__icon"></i>
      </div>
      <div class="form__body form__container form__hidden">
        <%= f.input :color %>
        <%= f.input :body_wood, collection: ['Alder','Basswood', 'Black Limba', 'Koa','Maple', 'Mohagany','Okoume', 'Swamp Ash', 'Walnut'] %>
        <%= f.input :body_top_wood, collection: ['Alder','Basswood', 'Black Limba', 'Koa','Maple', 'AAA Flamed Maple', 'Flamed Maple' ,'Quilted Maple', 'Mohagany', 'Poplar Burl','Okoume', 'Swamp Ash', 'Walnut', 'Zebra Wood', 'Carved AA Maple'] %>
        <%= f.input :body_finish %>
      </div>
      <div class="form__title form__title__pickups" data-name="form__pickups">
        <%= image_tag("icon-guitar-electronics.png") %>
        <h4>Pickups</h4>
        <i class="fa-solid fa-angle-down" id="form__pickups__icon"></i>
      </div>
      <div class="form__pickups form__container form__hidden">
        <%= f.input :pickups_configuration, hint:'HSH, SSS,...' %>
        <%= f.input :neck_pickup_id, label: 'Neck Pickup', collection: @pickups %>
        <%= f.input :center_pickup_id, label: 'Center Pickup', collection: @pickups %>
        <%= f.input :bridge_pickup_id, label: 'Bridge Pickup', collection: @pickups %>
      </div>
    </div>
    <div class="col-md">
      <div class="form__title form__title__neck" data-name="form__neck">
        <%= image_tag("icon-guitar-neck.png") %>
        <h4>Neck</h4>
        <i class="fa-solid fa-angle-down" id="form__neck__icon"></i>
      </div>
      <div class="form__neck form__container form__hidden">
        <%= f.input :neck_wood, collection: ['Alder','Basswood', 'Black Limba', 'Koa','Maple', 'Mohagany','Okoume', 'Swamp Ash', 'Walnut']  %>
        <%= f.input :fingerboard_wood, collection: ['Maple','Ebony', 'Rosewood', 'Richlite', 'Birdseye Maple', 'Roasted Maple', 'Flamed Maple'] %>
        <%= f.input :scale_length, label:'Scale Length (mm)' %>
        <%= f.input :neck_shape %>
        <%= f.input :neck_finish %>
        <%= f.input :neck_attachment %>
        <%= f.input :neck_radius, label:'Neck Radius (mm)' %>
        <%= f.input :neck_width_nut, label:'Neck Width At Nut (mm)' %>
        <%= f.input :neck_width_last_fret, label:'Neck Width At Last Fret (mm)' %>
        <%= f.input :frets_number, collection: 21..27 %>
        <%= f.input :frets_type %>
        <%= f.input :nut_material %>
      </div>
      <div class="form__title form__title__hardware" data-name="form__hardware">
        <%= image_tag("icon-guitar-hardware.png") %>
        <h4>Hardware</h4>
        <i class="fa-solid fa-angle-down" id="form__hardware__icon"></i>
      </div>
      <div class="form__hardware form__container form__hidden">
        <%= f.input :bridge %>
        <%= f.input :tuning_machines %>
      </div>
       <div class="form__title form__title__photos" data-name="form__photos">
        <%= image_tag("icon-guitar-photos.png") %>
        <h4>Photos</h4>
        <i class="fa-solid fa-angle-down" id="form__photos__icon"></i>
      </div>
      <div class="form__photos form__container form__hidden">
        <div class="form__photo">
          <%= f.input :photo, as: :file, label:'Main Photo', input_html: { id: 'main-photo', class:'photo-input' }%>
          <% if @guitar.photo_id %>
            <%= image_tag "http://res.cloudinary.com/drzsrupmq/image/upload/v1/development/#{@guitar.photo_id}", width: 200, id: "photo-main-photo" %>
          <% else %>
            <%= image_tag "", width: 200, class: "hidden", id: "photo-main-photo" %>
          <% end %>
        </div>
        <div class="form__photos">
          <div class="form__photo">
            <%= f.input :photos0, as: :file, input_html: { class:'photo-input', id:'input-1' }, label:'Secondary Photo 1' %>
            <% if @guitar.photos_ids[0] %>
              <%= image_tag "https://res.cloudinary.com/drzsrupmq/image/upload/v1661458045/GuitarList/#{@guitar.photos_ids[0]}", width: 200, id: "photo-input-1" %>
            <% else %>
              <%= image_tag "", width: 200, class: "hidden", id: "photo-input-1" %>
            <% end %>
          </div>
          <div class="form__photo">
            <%= f.input :photos1, as: :file, input_html: { class:'photo-input', id:'input-2' }, label:'Secondary Photo 2' %>
            <% if @guitar.photos_ids[1] %>
              <%= image_tag "https://res.cloudinary.com/drzsrupmq/image/upload/v1661458045/GuitarList/#{@guitar.photos_ids[1]}", width: 200, id: "photo-input-2" %>
            <% else %>
              <%= image_tag "", width: 200, class: "hidden", id: "photo-input-2" %>
            <% end %>
          </div>
          <div class="form__photo">
            <%= f.input :photos2, as: :file, input_html: { class:'photo-input', id:'input-3' }, label:'Secondary Photo 3' %>
            <% if @guitar.photos_ids[2] %>
              <%= image_tag "https://res.cloudinary.com/drzsrupmq/image/upload/v1661458045/GuitarList/#{@guitar.photos_ids[2]}", width: 200, id: "photo-input-3" %>
            <% else %>
              <%= image_tag "", width: 200, class: "hidden", id: "photo-input-3" %>
            <% end %>
          </div>
          <div class="form__photo">
            <%= f.input :photos3, as: :file, input_html: { class:'photo-input', id:'input-4' }, label:'Secondary Photo 4' %>
            <% if @guitar.photos_ids[3] %>
              <%= image_tag "https://res.cloudinary.com/drzsrupmq/image/upload/v1661458045/GuitarList/#{@guitar.photos_ids[3]}", width: 200, id: "photo-input-4" %>
            <% else %>
              <%= image_tag "", width: 200, class: "hidden", id: "photo-input-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form__submit__button">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/guitars/_table_body.html.erb
 <% guitars_categories.each do |guitar_category| %>
  <% cat = guitar_category[0].to_sym %>
  <tr>
    <th scope="col"><%= guitar_category[1] %></th>
    <% guitars.each do |guitar| %>
      <% case guitar_category[0] %>
      <% when 'neck_pickup_id' %>
        <% if guitar.neck_pickup_id %>
          <% pickup = Pickup.find(guitar.neck_pickup_id) %>
          <td><%= pickup.brand %> <%= pickup.name %></td>
        <% else %>
          <td></td>
        <% end %>
      <% when 'center_pickup_id' %>
        <% if guitar.center_pickup_id %>
          <% pickup = Pickup.find(guitar.center_pickup_id) %>
          <td><%= pickup.brand %> <%= pickup.name %></td>
        <% else %>
          <td></td>
        <% end %>
      <% when 'bridge_pickup_id' %>
        <% if guitar.bridge_pickup_id %>
          <% pickup = Pickup.find(guitar.bridge_pickup_id) %>
          <td><%= pickup.brand %> <%= pickup.name %></td>
        <% else %>
          <td></td>
        <% end %>
      <% when 'scale_length' || guitar_category[0] == 'neck_radius' || guitar_category[0] == 'neck_width_nut' || guitar_category[0] == 'neck_width_last_fret' %>
        <% if guitar.send(cat) %>
          <td><%= guitar.send(cat).round %>mm</td>
        <% else %>
          <td></td>
        <% end %>
      <% when 'price' %>
        <% if guitar.send(cat) %>
          <td><%= guitar.send(cat).round %>$</td>
        <% else %>
          <td></td>
        <% end %>
      <% else %>
        <td><%= guitar.send(cat) %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>

<tr class="table__photo__container">
  <th scope="col">Photo</th>
  <% guitars.each do |guitar| %>
    <td>
      <% if guitar.photo_id %>
        <div class="table__photo__content">
          <%= image_tag "http://res.cloudinary.com/drzsrupmq/image/upload/v1/development/#{guitar.photo_id}", class: "table__photo" %>
        </div>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/guitars/_table_helper.html.erb
<div class="table_helper">
  <div class="infos__helper table_helper__content">
    <i class="fa-solid fa-square"></i><h6>Infos</h6>
  </div>
  <div class="body__helper table_helper__content">
    <i class="fa-solid fa-square"></i><h6>Body</h6>
  </div>
  <div class="neck__helper table_helper__content">
    <i class="fa-solid fa-square"></i><h6>Neck</h6>
  </div>
  <div class="pickup__helper table_helper__content">
    <i class="fa-solid fa-square"></i><h6>Pickup</h6>
  </div>
  <div class="hardware__helper table_helper__content">
    <i class="fa-solid fa-square"></i><h6>Hardware</h6>
  </div>
</div>

app/views/guitars/edit.html.erb
<div class="container edit__container">
  <%= render 'shared/back_link' %>

  <h3>Editing <%= @guitar.brand %> <%= @guitar.name %></h3>

  <%= render 'form', guitar: @guitar %>

  <div class="delete-link-container">
    <button class='btn btn-danger' id='delete-button'>Delete</button>
    <%= link_to 'Delete', guitar_path(@guitar.id), method: :delete, class:'btn btn-danger d-none', id:'delete-link' %>
  </div>
</div>

app/views/guitars/index.html.erb
  <div class="table_container">
    <% unless @guitars.count.zero? %>
    <div class="table__xls__link">
      <%= link_to guitars_path(format: :xlsx) do %>
        <i class="fa-solid fa-download"></i>
      <% end %>
    </div>
    <% end %>
    <table>
      <thead>
        <tr>
        <th scope="col"> </th>
        <% @guitars.each do |guitar| %>
          <th scope="col"><%= guitar.name %></th>
        <% end %>
        </tr>
      </thead>
      <tbody>
        <%= render 'table_body', {guitars:@guitars, guitars_categories:@guitars_categories} %>
      </tbody>
    </table>
      <%= render 'table_helper' %>
  </div>

app/views/guitars/new.html.erb
<div class="container new__container">
  <%= render 'shared/back_link' %>
  
  <h3>New Guitar</h3>

  <%= render 'form', guitar: @guitar %>
</div>

app/views/guitars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_guitar_path(@guitar) %> |
<%= link_to 'Back', guitars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuitarListR7</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', "data-turbo-track": "reload", defer: true %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <%= favicon_link_tag %>
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>


    <% unless controller_name == 'sessions' && action_name == 'new' %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/flashes" %>

    <%= yield %>

    <%= yield :after_js %>

  </body>
</html>

app/views/pages/home.html.erb
<div id='guitar_list'></div>
<% content_for :after_js do %>
  <%= javascript_pack_tag "guitar_list" %>
<% end %>

app/views/pickups/_form.html.erb
<%= simple_form_for @pickup do |f| %>
  <%= f.input :brand, collection: PICKUP_BRANDS.sort %>
  <%= f.input :name %>
  <%= f.input :product_name %>
  <%= f.input :output, hint: 'in mV' %>
  <%= f.input :resistance, hint: 'in Kohm'%>
  <%= f.input :bass %>
  <%= f.input :low_middle %>
  <%= f.input :high_middle %>
  <%= f.input :treble %>
  <%= f.input :pickup_type, label: 'Type', collection: ['Single Coil', 'Humbucker', 'Humbucker in Single Coil', 'P90', 'Lipstick', 'Mini Humbucker'] %>
  <%= f.input :active %>
  <%= f.input :description %>
  <%= f.button :submit, class:'btn btn-primary' %>
<% end %>

app/views/pickups/new.html.erb
<div class="container new__container">
  <%= render 'shared/back_link' %>

  <h3>New pickup</h3>

  <%= render 'form', pickup: @pickup %>
</div>

app/views/shared/_back_link.html.erb
<div class="back_link">
  <%= link_to :back do %>
    <i class="fa-solid fa-angles-left"></i>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<% unless (controller_name == 'pages' && action_name == 'home') || controller_name == 'registrations' %>
  <div class="navbar navbar-guitarlist">
    <div class="navbar__item">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "logo.png", id:'nav__logo' %>
        <h4>GuitarList</h4>
      <% end %>
    </div>
    <div class="navbar__item" id="menu__bars">
      <div class="nav-item">
        <i class="fa-solid fa-bars"></i>
      </div>
    </div>
    <div class="nav-dropdown menu__hidden">
      <ul>
        <% if user_signed_in? %>
          <% unless (controller_name == 'pages' && action_name == 'home') %>
          <li class="nav-dropdown-item">
            <%= link_to 'Guitars', root_path %>
          </li>
          <% end %>
          <%= %>
          <li class="nav-dropdown-item">
            <%= link_to 'New Guitar', new_guitar_path %>
          </li>
          <li class="nav-dropdown-item">
            <%= link_to 'New Pickup', new_pickup_path %>
          </li>
          <li class="nav-dropdown-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <i id='menu__icon' class="fa-solid fa-arrow-right-from-bracket"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>